### ISSUE TITLE
fix heighliner

### ISSUE THREAD

**Issue by reecepbcups** [rollchains/spawn#30]
not sure why but when using heighliner to build, it's not picking up the fiels in the folder? used Juno as reference so I know it works, but it's not even building the binary

May need to modify chains.yml to be more specific like so:

```
- name: project
  github-organization: MY-ORG
  github-repo: myproject
  dockerfile: cosmos
  build-target: make install
  build-dir: ./
  build-env:
    - BUILD_TAGS=muslc
  binaries:
    - /go/bin/appd
```

ref: current `make local-image` uses standard docker builder.

also both break on wasmd builds because static linking stuff
permissiones for /tmp
